/**
 * Constants
 */
'use strict'

exports.VERSION = 5

exports.FLAG_PUBLISHED = 1
exports.FLAG_ATOM_CACHE = 2
exports.FLAG_EXTENDED_REFERENCES = 4
exports.FLAG_DIST_MONITOR = 8
exports.FLAG_FUN_TAGS = 0x10
exports.FLAG_DIST_MONITOR_NAME = 0x20
exports.FLAG_HIDDEN_ATOM_CACHE = 0x40
exports.FLAG_NEW_FUN_TAGS = 0x80
exports.FLAG_EXTENDED_PIDS_PORTS = 0x100
exports.FLAG_EXPORT_PTR_TAG = 0x200
exports.FLAG_BIT_BINARIES = 0x400
exports.FLAG_NEW_FLOATS = 0x800
exports.FLAG_UNICODE_IO = 0x1000
exports.FLAG_DIST_HDR_ATOM_CACHE = 0x2000
exports.FLAG_SMALL_ATOM_TAGS = 0x4000
exports.FLAG_UTF8_ATOMS = 0x10000
exports.FLAG_MAP_TAG = 0x20000
